[global]
bin = "./a.out"
timeout = 00:01:00

[[basic]]
[basic.foo]
fatal = true
args = ["--foo", "--bar", "--baz"]
code = 0
# stdin.value = "foo bar baz"
# stdin.end = "EOF"
stdout.mode = "match"
stdout.value = "foo\nbar\nbar\n"
stderr.mode = "empty"

[basic.timeout]
timeout = 00:00:02
args = ["--wait"]

[basic.bar]
code = 4
args = ["--zap"]
stdout.mode = "empty"
stderr.mode = "match"
stderr.value = "./a.out: --zap flag not recognized.*"

[[advanced]]
[advanced.bla]

[nani]
code = 42069
